In [188]:
#1. Import the NUMPY package under the name np.

#[your code here]
import numpy as np

In [189]:
#2. Print the NUMPY version and the configuration.

print(f"Version: {np.__version__}")

Version: 1.26.4


In [190]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Arnaldur/anaconda3/envs/original/Library/include
    lib directory: C:/Users/Arnaldur/anaconda3/envs/original/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
   

In [191]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

# the first one is generating random integers specifying the range and the size of the array

a = np.random.randint(10, size=(2, 3, 5))

#4. Print a.
print(a)

[[[1 0 2 9 7]
  [1 1 0 0 4]
  [4 3 9 1 5]]

 [[5 9 2 5 1]
  [1 6 1 9 3]
  [6 8 7 1 2]]]


In [192]:
# the second one is generating random floats (between 0 and 1) specifying the number of elements
# we need to find out the size first

print(np.size(a))

# or we can also do that:
size = 2*3*5
print(f"size = {size}")

30
size = 30


In [217]:
# now we generate the array with the 30 random floats between 0 and 1

afloat = np.random.random(30)
afloat_round = np.round(afloat, 2)
afloat_round


array([0.32, 0.76, 0.73, 0.64, 0.61, 0.67, 0.79, 0.28, 0.21, 0.12, 0.03,
       0.52, 0.01, 0.72, 0.2 , 0.9 , 0.5 , 0.49, 0.05, 0.45, 0.13, 0.66,
       0.9 , 0.93, 0.69, 0.98, 0.39, 0.97, 0.38, 0.27])

In [218]:
# we have a vector of 30 elements, so we have to reshape it to the desired size

a2 = np.reshape(afloat_round, (2,3,5))

#4. Print a.
a2

array([[[0.32, 0.76, 0.73, 0.64, 0.61],
        [0.67, 0.79, 0.28, 0.21, 0.12],
        [0.03, 0.52, 0.01, 0.72, 0.2 ]],

       [[0.9 , 0.5 , 0.49, 0.05, 0.45],
        [0.13, 0.66, 0.9 , 0.93, 0.69],
        [0.98, 0.39, 0.97, 0.38, 0.27]]])

In [219]:
# the third way is to create a random array of floats between 2 specificed values

a3 = np.round(np.random.uniform(1,11, (2,3,5)), 2)
a3

array([[[ 8.4 ,  1.86, 10.17,  5.53,  2.84],
        [ 5.78,  6.36,  9.37,  8.26,  9.13],
        [ 2.18,  7.8 ,  3.93,  2.25,  9.11]],

       [[ 3.82,  8.28, 10.04,  7.83,  2.42],
        [10.83,  7.63,  8.  ,  4.39,  1.07],
        [ 1.58,  9.33,  4.54,  1.16,  7.64]]])

In [220]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3), dtype=int)

#6. Print b.
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [221]:
#7. Do a and b have the same size? How do you prove that in Python code?

np.size(a) == np.size(b)

True

In [222]:
#8. Are you able to add a and b? Why or why not?

# No, because their shapes are different

print(np.shape(a))
print(np.shape(b))

(2, 3, 5)
(5, 2, 3)


In [223]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.reshape(b, (2,3,5))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [224]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". 

a

array([[[1, 0, 2, 9, 7],
        [1, 1, 0, 0, 4],
        [4, 3, 9, 1, 5]],

       [[5, 9, 2, 5, 1],
        [1, 6, 1, 9, 3],
        [6, 8, 7, 1, 2]]])

In [225]:
d = a + c
d

array([[[ 2,  1,  3, 10,  8],
        [ 2,  2,  1,  1,  5],
        [ 5,  4, 10,  2,  6]],

       [[ 6, 10,  3,  6,  2],
        [ 2,  7,  2, 10,  4],
        [ 7,  9,  8,  2,  3]]])

In [226]:
# But why does it work now?

# Because now they have the same shape
print(np.shape(a))
print(np.shape(c))

(2, 3, 5)
(2, 3, 5)


In [227]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)

[[[1 0 2 9 7]
  [1 1 0 0 4]
  [4 3 9 1 5]]

 [[5 9 2 5 1]
  [1 6 1 9 3]
  [6 8 7 1 2]]]
[[[ 2  1  3 10  8]
  [ 2  2  1  1  5]
  [ 5  4 10  2  6]]

 [[ 6 10  3  6  2]
  [ 2  7  2 10  4]
  [ 7  9  8  2  3]]]


In [228]:
# They are almost the same, we have only added the "b" array to the "a1", so basically d = a1 + 1

In [229]:
print(a + 1)
print(d)

[[[ 2  1  3 10  8]
  [ 2  2  1  1  5]
  [ 5  4 10  2  6]]

 [[ 6 10  3  6  2]
  [ 2  7  2 10  4]
  [ 7  9  8  2  3]]]
[[[ 2  1  3 10  8]
  [ 2  2  1  1  5]
  [ 5  4 10  2  6]]

 [[ 6 10  3  6  2]
  [ 2  7  2 10  4]
  [ 7  9  8  2  3]]]


In [230]:
d == a + 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [231]:
#12. Multiply a and c. Assign the result to e.

e = a*c
e

array([[[1, 0, 2, 9, 7],
        [1, 1, 0, 0, 4],
        [4, 3, 9, 1, 5]],

       [[5, 9, 2, 5, 1],
        [1, 6, 1, 9, 3],
        [6, 8, 7, 1, 2]]])

In [232]:
#13. Does e equal to a? Why or why not?

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [233]:
# Yes, because:
# a = original random array
# b = array of ones
# c = b reshaped
# e = a*c = 'a' array * 1

In [234]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
print(d)

[[[ 2  1  3 10  8]
  [ 2  2  1  1  5]
  [ 5  4 10  2  6]]

 [[ 6 10  3  6  2]
  [ 2  7  2 10  4]
  [ 7  9  8  2  3]]]


In [291]:
d_max = np.max(d)
print(f"Max: {d_max}")
d_min = np.min(d)
print(f"Min: {d_min}")
d_mean = np.mean(d)
print(f"Mean: {d_mean}")

Max: 10
Min: 1
Mean: 4.766666666666667


In [249]:
# The mean is technically the following, even though is longer and more complicated
mitjana = sum(sum(sum(d)))/np.size(d)
mitjana

4.766666666666667

In [255]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f1 = np.empty((2,3,5), dtype=int)
print(f1)

[[[      0       0       0       0       0]
  [      0       0       0       0       0]
  [      0       0       0       0       0]]

 [[      0       0       0       0       0]
  [      0       0       0       0       0]
  [      0       0       0 6619243 8192116]]]


In [257]:
# it generates me a new array with the same size but with garbage values that has stored previously
# so we can just create a new array with zeros

f = np.zeros((2,3,5), dtype=int)
print(f)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [215]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
task= '''
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
'''

In [272]:
print(d)

[[[ 2  1  3 10  8]
  [ 2  2  1  1  5]
  [ 5  4 10  2  6]]

 [[ 6 10  3  6  2]
  [ 2  7  2 10  4]
  [ 7  9  8  2  3]]]


In [289]:
print(f"Max: {d_max}")
print(f"Min: {d_min}")
print(f"Mean: {d_mean}")

Max: 10
Min: 1
Mean: 4.766666666666667


In [288]:
f[d < d_mean] = 25
f[d > d_mean] = 75
f[d == d_max] = 100
f[d == d_mean] = 50
f[d == d_min] = 0
print(f)

[[[ 25   0  25 100  75]
  [ 25  25   0   0  75]
  [ 75  25 100  25  75]]

 [[ 75 100  25  75  25]
  [ 25  75  25 100  25]
  [ 75  75  75  25  25]]]


In [295]:
#17. Print d and f. Do you have your expected f?
task='''
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
'''

In [297]:
d = ([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
d


[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
  [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
  [1.72201435, 1.1862918, 1.87078449, 1.7726778, 1.88180042]],
 [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
  [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
  [1.18068344, 1.9587381, 1.00656599, 1.93402165, 1.73514584]]]

In [301]:
d_max = np.max(d)
print(f"Max: {d_max}")
d_min = np.min(d)
print(f"Min: {d_min}")
d_mean = np.mean(d)
print(f"Mean: {d_mean}")

Max: 1.97066381
Min: 1.00656599
Mean: 1.6175069086666667


In [310]:
f[d < d_mean] = 25
f[d > d_mean] = 75
f[d == d_max] = 100
f[d == d_mean] = 50
f[d == d_min] = 0
print(f)

damn ='''
Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
'''

[[[ 75  75  75  25  75]
  [ 75  75  25  25  25]
  [ 75  25  75  75  75]]

 [[ 25  25  25  25 100]
  [ 75  75  75  75  75]
  [ 25  75   0  75  75]]]


In [313]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
enunciat = """
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [340]:
g = np.zeros((2,3,5), dtype='<U5')

In [342]:
g[f == 25] = 'B'
g[f == 75] = 'D'
g[f == 100] = 'E'
g[f == 0] = 'A'
print(g)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
